#----------------------
# About section

blurb: <p> I am Jude Kong an <em> NSERC Postdoctoral Fellow.<\em> I earned my PhD in Applied Mathematics along side an embbeded certificate in Data Science from the University of Alberta.<\p>

#----------------------
# Courses section
courses:
  - {title: Intro to Chem, semester: Fall 1885, school: King's College London, description: Teaching students chemistry isn't only for witches., link: courses/temp_course }
  - {title: Advanced Psychiatric Medicine, semester: Spring 1885, school: King's College London, description: At the time, mainly lobotomy., link: courses/temp_course }
  - {title: Diseases of the Mind, semester: Fall 1884, school: King's College London, description: Survey course. Mainly taught by example., link: courses/temp_course }
#----------------------
# Contact
contact-info: <p>Henry Jekyll<br>King's College London<br>Department of Chemistry<br>Strand<br>London<br>WC2R 2LS<br>United Kingdom</p>

contact-links:
  - {contact-text: Github, contact-link: "https://www.google.com", icon: 'favicon.html'}
